# name: Deploy to Google Cloud Run
# 
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main
# 
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/cozycozy-scraper:${{ github.sha }}
#     - name: Push Docker image to Google Container Registry
#       run: |
#         echo ${{ secrets.GCR_JSON_KEY }} | docker login -u _json_key --password-stdin https://gcr.io
#         docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/cozycozy-scraper:${{ github.sha }}
# 
#   deploy:
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#     - name: Deploy to Google Cloud Run
#       run: |
#         gcloud run deploy cozycozy-scraper --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/cozycozy-scraper:${{ github.sha }} --platform managed --region us-central1
#       env:
#         GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
#         GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
# 